version: '2'
services:
  db:
    container_name: kotlin-websocket-db
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: superdupersecret
      MYSQL_DATABASE: music-store

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080